# General colors
foreground #d0d0d0
background #1e1e2e

# Selected colors
selection_foreground #ffffff
selection_background #44475a

# Cursor colors
cursor #d0d0d0
cursor_text_color #1e1e2e


# ANSI colors
color0  #1f1f1f
color8  #c0bfbc

color1  #ff7f7f
color9  #ff5454

color2  #8ff0a4
color10 #7aff81

color3  #f6d32d
color11 #fff34f

color4  #99c1f1
color12 #90caf9

color5  #eb83bc
color13 #ff66c4

color6  #83ebe8
color14 #73ffef

color7  #f0f0f0
color15 #ffffff


# Marks colors
mark1_foreground black
mark1_background #98d3cb

mark2_foreground black
mark2_background #f2dcd3

mark3_foreground black
mark3_background #f274bc
