# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    preserve_split = true # You probably want this
    force_split = 2 # Menentukan arah jendela yang akan dibuka
    smart_split = false # Menentukan arah jendela terbuka dari letak kursor
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}
