#################################
### Konfigurasi Submap Resize ###
#################################

bind = SUPER, D, submap, resize

submap = resize
binde = , H, resizeactive, -30 0
binde = , J, resizeactive, 0 30
binde = , K, resizeactive, 0 -30
binde = , L, resizeactive, 30 0

bind = , ESCAPE, submap, reset 
bind = , RETURN, submap, reset
submap = reset
