greeting_msg = "Welcome to Arch Linux"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[background]
path = "/usr/share/backgrounds/regreet.jpg"
fit = "Cover"

[GTK]
apllication_prefer_dark_theme = true
theme_name = "Adwaita-dark"
icon_theme_name = "Adwaita"
cursor_theme_name = "Adwaita"
